version: "3.8" 

services:
#  cook18_react: 
#    build: 
#      context: ./ui_ts
#      dockerfile: Dockerfile.dev
#    container_name: cook18_react
#    volumes:
#      - ./ui_ts:/ui_ts
#      - /ui_ts/node_modules
#    ports:
#      - "4218:4200" 
#      - "49153:49153"
#    environment:
#      - NODE_ENV=dev
#    networks:
#      - default 

  cook18_ts:
    build:
      context: ./api_ts
      dockerfile: Dockerfile.dev
    container_name: cook18_ts
    volumes:
      - ./api_ts:/api_ts
      - /api_ts/node_modules
    ports:
      - "6018:3000"
    networks:
      - default 
#    depends_on:
#      - cook17_database
#      - cook17_mongo


networks:
  default:
