version: "3.8" 

services:
#  cook18_react_ts: 
#    build: 
#      context: ./ui
#      dockerfile: Dockerfile.dev
#    container_name: cook18_react_ts
#    volumes:
#      - ./ui:/ui
#      - /ui/node_modules
#    ports:
#      - "4218:4200" 
#      - "49153:49153"
#    environment:
#      - NODE_ENV=dev
#    networks:
#      - default 

  cook18_ts:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: cook18_ts
    volumes:
      - ./api:/api
      - /api/node_modules
    ports:
      - "6018:3000"
    environment:
      - NODE_ENV=dev
    networks:
      - default 
    depends_on:
#      - cook18_database
      - cook18_mongo

  cook18_mongo:
    image: mongo
    #restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - default 

  cook18_mongo_admin:
    image: mongo-express
    #restart: always
    ports:
      - 10018:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - default 
    depends_on:
      - cook18_mongo


networks:
  default:
